language: node_js
node_js:
 - "8.4.0"
branches:
  only:
    - develop
script:
 - npm test
services:
  - postgresql
env:
  - SECRET_TOKEN=tokensecret
before_script:
  - psql -c 'CREATE DATABASE travis;' -U postgres
before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start